/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/customers": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.customers.id"];
          stripe_customer_id?: parameters["rowFilter.customers.stripe_customer_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["customers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** customers */
          customers?: definitions["customers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.customers.id"];
          stripe_customer_id?: parameters["rowFilter.customers.stripe_customer_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.customers.id"];
          stripe_customer_id?: parameters["rowFilter.customers.stripe_customer_id"];
        };
        body: {
          /** customers */
          customers?: definitions["customers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/prices": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.prices.id"];
          product_id?: parameters["rowFilter.prices.product_id"];
          active?: parameters["rowFilter.prices.active"];
          description?: parameters["rowFilter.prices.description"];
          unit_amount?: parameters["rowFilter.prices.unit_amount"];
          currency?: parameters["rowFilter.prices.currency"];
          type?: parameters["rowFilter.prices.type"];
          interval?: parameters["rowFilter.prices.interval"];
          interval_count?: parameters["rowFilter.prices.interval_count"];
          trial_period_days?: parameters["rowFilter.prices.trial_period_days"];
          metadata?: parameters["rowFilter.prices.metadata"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["prices"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** prices */
          prices?: definitions["prices"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.prices.id"];
          product_id?: parameters["rowFilter.prices.product_id"];
          active?: parameters["rowFilter.prices.active"];
          description?: parameters["rowFilter.prices.description"];
          unit_amount?: parameters["rowFilter.prices.unit_amount"];
          currency?: parameters["rowFilter.prices.currency"];
          type?: parameters["rowFilter.prices.type"];
          interval?: parameters["rowFilter.prices.interval"];
          interval_count?: parameters["rowFilter.prices.interval_count"];
          trial_period_days?: parameters["rowFilter.prices.trial_period_days"];
          metadata?: parameters["rowFilter.prices.metadata"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.prices.id"];
          product_id?: parameters["rowFilter.prices.product_id"];
          active?: parameters["rowFilter.prices.active"];
          description?: parameters["rowFilter.prices.description"];
          unit_amount?: parameters["rowFilter.prices.unit_amount"];
          currency?: parameters["rowFilter.prices.currency"];
          type?: parameters["rowFilter.prices.type"];
          interval?: parameters["rowFilter.prices.interval"];
          interval_count?: parameters["rowFilter.prices.interval_count"];
          trial_period_days?: parameters["rowFilter.prices.trial_period_days"];
          metadata?: parameters["rowFilter.prices.metadata"];
        };
        body: {
          /** prices */
          prices?: definitions["prices"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          active?: parameters["rowFilter.products.active"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          image?: parameters["rowFilter.products.image"];
          metadata?: parameters["rowFilter.products.metadata"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          active?: parameters["rowFilter.products.active"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          image?: parameters["rowFilter.products.image"];
          metadata?: parameters["rowFilter.products.metadata"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          active?: parameters["rowFilter.products.active"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          image?: parameters["rowFilter.products.image"];
          metadata?: parameters["rowFilter.products.metadata"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/subscriptions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          user_id?: parameters["rowFilter.subscriptions.user_id"];
          status?: parameters["rowFilter.subscriptions.status"];
          metadata?: parameters["rowFilter.subscriptions.metadata"];
          price_id?: parameters["rowFilter.subscriptions.price_id"];
          quantity?: parameters["rowFilter.subscriptions.quantity"];
          cancel_at_period_end?: parameters["rowFilter.subscriptions.cancel_at_period_end"];
          created?: parameters["rowFilter.subscriptions.created"];
          current_period_start?: parameters["rowFilter.subscriptions.current_period_start"];
          current_period_end?: parameters["rowFilter.subscriptions.current_period_end"];
          ended_at?: parameters["rowFilter.subscriptions.ended_at"];
          cancel_at?: parameters["rowFilter.subscriptions.cancel_at"];
          canceled_at?: parameters["rowFilter.subscriptions.canceled_at"];
          trial_start?: parameters["rowFilter.subscriptions.trial_start"];
          trial_end?: parameters["rowFilter.subscriptions.trial_end"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["subscriptions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          user_id?: parameters["rowFilter.subscriptions.user_id"];
          status?: parameters["rowFilter.subscriptions.status"];
          metadata?: parameters["rowFilter.subscriptions.metadata"];
          price_id?: parameters["rowFilter.subscriptions.price_id"];
          quantity?: parameters["rowFilter.subscriptions.quantity"];
          cancel_at_period_end?: parameters["rowFilter.subscriptions.cancel_at_period_end"];
          created?: parameters["rowFilter.subscriptions.created"];
          current_period_start?: parameters["rowFilter.subscriptions.current_period_start"];
          current_period_end?: parameters["rowFilter.subscriptions.current_period_end"];
          ended_at?: parameters["rowFilter.subscriptions.ended_at"];
          cancel_at?: parameters["rowFilter.subscriptions.cancel_at"];
          canceled_at?: parameters["rowFilter.subscriptions.canceled_at"];
          trial_start?: parameters["rowFilter.subscriptions.trial_start"];
          trial_end?: parameters["rowFilter.subscriptions.trial_end"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          user_id?: parameters["rowFilter.subscriptions.user_id"];
          status?: parameters["rowFilter.subscriptions.status"];
          metadata?: parameters["rowFilter.subscriptions.metadata"];
          price_id?: parameters["rowFilter.subscriptions.price_id"];
          quantity?: parameters["rowFilter.subscriptions.quantity"];
          cancel_at_period_end?: parameters["rowFilter.subscriptions.cancel_at_period_end"];
          created?: parameters["rowFilter.subscriptions.created"];
          current_period_start?: parameters["rowFilter.subscriptions.current_period_start"];
          current_period_end?: parameters["rowFilter.subscriptions.current_period_end"];
          ended_at?: parameters["rowFilter.subscriptions.ended_at"];
          cancel_at?: parameters["rowFilter.subscriptions.cancel_at"];
          canceled_at?: parameters["rowFilter.subscriptions.canceled_at"];
          trial_start?: parameters["rowFilter.subscriptions.trial_start"];
          trial_end?: parameters["rowFilter.subscriptions.trial_end"];
        };
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          full_name?: parameters["rowFilter.users.full_name"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          billing_address?: parameters["rowFilter.users.billing_address"];
          payment_method?: parameters["rowFilter.users.payment_method"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          full_name?: parameters["rowFilter.users.full_name"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          billing_address?: parameters["rowFilter.users.billing_address"];
          payment_method?: parameters["rowFilter.users.payment_method"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          full_name?: parameters["rowFilter.users.full_name"];
          avatar_url?: parameters["rowFilter.users.avatar_url"];
          billing_address?: parameters["rowFilter.users.billing_address"];
          payment_method?: parameters["rowFilter.users.payment_method"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/handle_new_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: any };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  customers: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    id: string;
    stripe_customer_id?: string;
  };
  prices: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `products.id`.<fk table='products' column='id'/>
     */
    product_id?: string;
    active?: boolean;
    description?: string;
    unit_amount?: number;
    currency?: string;
    type?: "one_time" | "recurring";
    interval?: "day" | "week" | "month" | "year";
    interval_count?: number;
    trial_period_days?: number;
    metadata?: string;
  };
  products: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    active?: boolean;
    name?: string;
    description?: string;
    image?: string;
    metadata?: string;
  };
  subscriptions: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    status?:
      | "trialing"
      | "active"
      | "canceled"
      | "incomplete"
      | "incomplete_expired"
      | "past_due"
      | "unpaid";
    metadata?: string;
    /**
     * Note:
     * This is a Foreign Key to `prices.id`.<fk table='prices' column='id'/>
     */
    price_id?: string;
    quantity?: number;
    cancel_at_period_end?: boolean;
    created: string;
    current_period_start: string;
    current_period_end: string;
    ended_at?: string;
    cancel_at?: string;
    canceled_at?: string;
    trial_start?: string;
    trial_end?: string;
  };
  users: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    id: string;
    full_name?: string;
    avatar_url?: string;
    billing_address?: string;
    payment_method?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** customers */
  "body.customers": definitions["customers"];
  "rowFilter.customers.id": string;
  "rowFilter.customers.stripe_customer_id": string;
  /** prices */
  "body.prices": definitions["prices"];
  "rowFilter.prices.id": string;
  "rowFilter.prices.product_id": string;
  "rowFilter.prices.active": string;
  "rowFilter.prices.description": string;
  "rowFilter.prices.unit_amount": string;
  "rowFilter.prices.currency": string;
  "rowFilter.prices.type": string;
  "rowFilter.prices.interval": string;
  "rowFilter.prices.interval_count": string;
  "rowFilter.prices.trial_period_days": string;
  "rowFilter.prices.metadata": string;
  /** products */
  "body.products": definitions["products"];
  "rowFilter.products.id": string;
  "rowFilter.products.active": string;
  "rowFilter.products.name": string;
  "rowFilter.products.description": string;
  "rowFilter.products.image": string;
  "rowFilter.products.metadata": string;
  /** subscriptions */
  "body.subscriptions": definitions["subscriptions"];
  "rowFilter.subscriptions.id": string;
  "rowFilter.subscriptions.user_id": string;
  "rowFilter.subscriptions.status": string;
  "rowFilter.subscriptions.metadata": string;
  "rowFilter.subscriptions.price_id": string;
  "rowFilter.subscriptions.quantity": string;
  "rowFilter.subscriptions.cancel_at_period_end": string;
  "rowFilter.subscriptions.created": string;
  "rowFilter.subscriptions.current_period_start": string;
  "rowFilter.subscriptions.current_period_end": string;
  "rowFilter.subscriptions.ended_at": string;
  "rowFilter.subscriptions.cancel_at": string;
  "rowFilter.subscriptions.canceled_at": string;
  "rowFilter.subscriptions.trial_start": string;
  "rowFilter.subscriptions.trial_end": string;
  /** users */
  "body.users": definitions["users"];
  "rowFilter.users.id": string;
  "rowFilter.users.full_name": string;
  "rowFilter.users.avatar_url": string;
  "rowFilter.users.billing_address": string;
  "rowFilter.users.payment_method": string;
}

export interface operations {}
